# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache pip
      uses: actions/cache@v1
      with:
       path: ~/.cache/pip # This path is specific to Ubuntu
       # Look to see if there is a cache hit for the corresponding requirements file
       key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
       restore-keys: |
         ${{ runner.os }}-pip-
         ${{ runner.os }}-
    # You can test your matrix by printing the current Python version
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 mypy pytest hypothesis isort pylint
    - name: Run black
      run:
        black --check . --exclude docs/
    - name: Run flake8
      run: flake8 fizzbuzz.py
    - name: Run pylint
      run: pylint fizzbuzz.py
    - name: Run Mypy
      run: mypy fizzbuzz.py
    - name: Run isort
      run: isort --profile black fizzbuzz.py
    - name: tests
      run: pytest
    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: app.yaml
        version: v1
        project_id: techam-366201
        credentials: { "type": "service_account", "project_id": "techam-366201", "private_key_id": "03868c931984d78d163627d709201b5b07d562e9", "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCmnkiTLZ8FUf6h\nwDQ4STCl2kmFLHGQw2muA1NgzIjs7LtjCOcWehliANGU1QuZvNBihjIBz1Y6/ydN\n/9g/bNqCfjoSfPzPNrcfSQPYgEoVmpwGcKgAwhWhQ5jfroc1DRwl7v68ahpzheQz\nxoyfXsGrMx90IfrmIvm9Z04bfjFXFIyxHqU8uWkh6kii5qu68ACI0t5TZZDLF4qf\ntDbDf0W7Kk30Drz4fAifW7ssDFw9zGhvfwPx1PMjiihVM68mnSb2CyniztOd38Xn\nymQb2l6/bE3J3Ra5AOaBKrnJbukTQtnPpNJy/TdAjTjFh/WPu30vEryP+8bdpTs6\n0PXgZOFnAgMBAAECggEAUtqkEVge2yjue+XVseWnZNobNDepE4kxDKDHvfuH3XVN\nK466R2GZLLRmg+G7XoxXfZ7o0CCX60eFdpKSqNuK/1ggrZ/soWg+gLawzGDjNkIH\nc2ZjDNl2oxY3t4eU4asuw6hIkU4b8DV1CNAjjn6yxNzrt7bMCtP6p5Zu71n91CRr\nzqDrrBcdfhERgvhWXkzXrRnsN2xTS7NgxlV3lmvl+fyue/hggRAOoRra8A66+1r+\nVE4mdUxWmbWad6jHCIQN1iAOJzgY2hyHOm2x7Yzjv5dwQ1N52Q7iLXNgwFExb1aZ\nV49MUDEursHChgcJmipGHAx0SeZMTTYAUyDEowE9KQKBgQDlt4dPts86oSjClpJx\nnYyEdFX8lE7Bv7lV1R6Vidn6ThkcZWx0YWg8rktKy3WGaTTO5TyVkLiZlPjjrmv7\nhy/3fOtLWkm3bQgwEvBuzlpS3WZiEkN+kjOomPHQgpdB6BZCyMNrjx3AWOTb5kWf\nfMMDnhVwhTlUuTx/+o7a6FqerwKBgQC5rpRFpsJo38rvA6FmDmQmDaIgDEdeUx/s\n/Qd+Kvre+AyxVoZQo2vjZ3WTVIGmNQIascWSu+lhrs3Qu5o/2mU+sf5kSoAfF3hx\neTxZzShvG26a/n/9GIDW4+TDhs73jTU7uDtxtft6OGcURXC1e52nXTX2Y5sr+Ijx\nGRdMvujWyQKBgQCowys6afBWf11lj58orvkzuhANzpsJhiPPphGhBLRKSqPyE6UY\n3xLoOZgA6/Z8d8AfG5RlwPuNgT9UbajREiEwLeri4gL0KbrxLojKrvj2lccI16gU\nTa5791j3uWkMN0hbagj/dRYDYItJ7iNKJytR9gqELqvOzYNf9iCLPFaO6wKBgQCU\nEKajtAqq3mpQljCJ1Uf/IDf8Hk565QY8ULk83sEWM+7LKxgIDYjm2YVkaqrIAtUe\nvEu0aqv7/QyaOj8SU/EQQZd+Gfp40Jp2whph8bsgfluAtRkSlguHUEsHr+QyeyPL\n72lXj6ptF7T68TSjQ2PAJg/13g/KzHFG8J8nz8SUIQKBgD0B1dk1hr+l1lGrtx9Q\nCc/SX9zFYzQOjHTWV+mUs+sy3Xs/qOJZx1kFeqzUDH022vbjacVa906qZcmHfbzw\noSmM5CYdL9ot8D0fCGUZS3SzPNuT0QTKSI5wQJ12EqV55qPhYSkurQ9/l+mNoTb2\n2BwUuG9nSdtJZwMmcM2/h/95\n-----END PRIVATE KEY-----\n", "client_email": "techam-service-account@techam-366201.iam.gserviceaccount.com", "client_id": "114806167266112351812", "auth_uri": "https://accounts.google.com/o/oauth2/auth", "token_uri": "https://oauth2.googleapis.com/token", "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs", "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/techam-service-account%40techam-366201.iam.gserviceaccount.com" }
    - name: Test
      run: curl "${{ steps.deploy.outputs.url }}"
